#!/bin/bash

#get the starting time in milliseconds
START=$(date +%s%3N)

#store where the markdown files are, and where to put the converted one at
MD_FOLDER="$HOME/Documents/Obsidian/Mr.Tinkerer/Blogs"
BLOG_FOLDER="$HOME/Documents/Mr.Tinkerer/content/posts"

#create the blog folder if it doesn't exist
if [[ ! -e $BLOG_FOLDER ]]; then
    mkdir -p $BLOG_FOLDER
    echo "Created the blog folder."
fi

#The slug file for storing the file's name and their slug assoications
SLUG_FILE="$BLOG_FOLDER/../../slug.txt"

#delete the file before creating it. easier then checking what's already in there and not adding it
if [[ -e "$SLUG_FILE" ]]; then
    rm $SLUG_FILE
fi
touch $SLUG_FILE

#get all of the markdown files in the obsidian folder, and loop over it
find $MD_FOLDER -name "*.md" | while IFS= read -r line; do
    #get the slug name, and the basename of the file
    slug=$(grep "slug: " "$line" --max-count 1)
    md_file=$(basename "$line")

    #format the output and append it to the file
    echo "$md_file|$slug" >> $SLUG_FILE
done

#list of markdowns that will be converted
mds_to_convert=()

#go through all of the folders in the markdown folder, and get the basename
for md in $MD_FOLDER/*; do
    md_base=$(basename "$md")

    #skip looking into the blog folder if it's empty
    if [[ -n $(ls -A $BLOG_FOLDER) ]]; then

        #assumes that the blog doesnt exist
        ADD=true

        #go through all of the folders in the blog folder, and get the basename
        for blog in $BLOG_FOLDER/*; do
            blog_base=$(basename "$blog")

            # if the markdown base does exist in the blog, then skip it
            if [[ $md_base == $blog_base ]]; then
                ADD=false
                continue
            fi
        done

        #add the markdown to the list of conversion
        if [[ $ADD = true ]]; then
            echo "'$md_base' doesn't have a blog, yet"
            mds_to_convert+=("$md_base")
        fi

    else
        #auto add it to the list, since the blog folder is empty
        mds_to_convert+=("$md_base")
    fi
done

#copy over each article to the blog folder
for md_article in "${mds_to_convert[@]}"; do
    #copy the markdown's article folder to the blog folder
    md_path="$MD_FOLDER/$md_article"
    cp -r "$md_path" "$BLOG_FOLDER"
    echo "Copied over the $md_article over to the blog folder."

    #go into the blog article path
    cd "$BLOG_FOLDER/$md_article"

    #renamed the .md file into index.md for hugo
    for file in *.md; do
            mv "$file" index.md
            echo "Renamed '$file' to index.md"
            break
    done

    #replace all heading 1 (#) with heading 2 (##) for the table of contents to work
    sed -i "s/^# /## /g" index.md
    echo "Fixed the table of contents for $md_article"

    #iter through every obsidian backlink for images
    #(NOTE: this line was generated by Google's Gemini cause I couldn't figure out how to do it by hand)
    grep -oP '(?<=!\[\[).*?(?=\]\])' index.md | while IFS= read -r line; do
        #replace spaces with %20 for compability
        safe_img=$(echo $line | sed "s/ /%20/g")

        #replace all of the obsidian backlink with markdown link with the safe version
        sed -i -E "s/!\[\[$line\]\]/![]($safe_img)/" index.md
    done
    echo "Fixed the images for $md_article"

    #iter through every obsidian backlink for articles
    #(NOTE: this line was generated by Google's Gemini cause I couldn't figure out how to do it by hand)
    grep -oP '\[\[\K[^\]]*\|[^\]]*(?=\]\])' index.md | while IFS= read -r line; do
        #split the line into the file part, and the alt text part
        link_file=$(echo "$line" | awk -F '|' '{print $1}')
        alt_text=$(echo "$line" | awk -F '|' '{print $2}')

        #look for the slug that's for the file referenced, extract it, lowercase it, and replace all spaces with -
        slug_result=$(grep "$link_file" $SLUG_FILE)
        slug=$(echo $slug_result | awk -F '|slug: ' '{print tolower($2)}')
        slug=$(echo $slug | sed "s/ /-/g")

        #create the markdown version of the link
        new_link="[$alt_text](\/posts\/$slug)"

        #replace the obsidian backlink with the markdown link
        sed -i "s/\[\[$line\]\]/$new_link/" index.md
    done
    echo "Fixed the backlinsk for $md_article"

    #extract the tags from the file
    #(NOTE: this line was generated by Google's Gemini cause I couldn't figure out how to do it by hand)
    front_matter=$(awk '/^---$/ {p++; next} p==1 {print}' index.md)
    tags=$(echo "$front_matter" | grep "^  - ")

    #replace the tag's _ with spaces
    echo "$tags" | while IFS= read -r line; do
        new_tag=$(echo "$line" | sed "s/_/ /")
        sed -i "s/$line/$new_tag/" index.md
    done
    echo "Fixed tags for $md_article"

    #divider to seperate the blogs when reading the output
    echo "------------------------------------------------"
done

#prepare the commit message
commit="Created the blogs for '"

#get the internal name for the blog, and add it to the commit msg
for md_folder in "${mds_to_convert[@]}"; do
    blog=$(echo "$md_folder" | awk -F " - " '{print $2}')
    commit+="$blog, "
done

#remove the last two characters, and finish the message
commit="${commit%??}"
commit+="' blogs."


#generate the static site
cd "$BLOG_FOLDER/../.."
hugo --cleanDestinationDir --gc

#make the commits to the branch
git add *
git commit -m "$commit"

#push them to github
git push -u origin main

#caculate how long the script take to execute, and say it
END=$(date +%s%3N)
duration=$(( END - START ))